version: '3'
 
services:
    phpreactive:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/srv/www/api
        ports:
            - 8000:8000
    mysqlreactive:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        ports:
            - 3306:3306
        depends_on:
            - phpreactive
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ejemplo
            MYSQL_USER: user
            MYSQL_PASSWORD: user